### PR TITLE
Create requirements.txt

### LINKED ISSUE #31: document python library dependencies in central location
Ideally, all python library dependencies would be included in the condaenv.yml, or an equivalent file such as a requirements.txt.

### PR DESCRIPTION
**Pull request by AbhishekSrikanth**
### This solves issue #31 

- Added requirements.txt

### CODE REVIEW

**Comment by mdbernard** [comment]
Could you add a setup.py making use of this as well? That'd be optimal for an easy setup.

**Comment by AbhishekSrikanth** [comment]
Are you sure that you want a setup.py file? It's used for installing python packages. I believe this is just a repo, correct me if I'm wrong. Users can right now use the requirements.txt file to install dependencies. You can include instructions for that in the documentation.

**Comment by mdbernard** [comment]
~~Yes. We typically have a lot of beginner programmers on the team, so it's beneficial to have a setup.py to ease them into things.~~

**Comment by mdbernard** [comment]
Disregard that, we don't need a setup.py.

**Pull request merged**
